---
name: Variables de entorno
on: [push]
env:
  WF_ENV: Global Variable
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Job Variable
    steps:
      - name: paso1
        env:
          STEP_ENV: Step Variable
        run: |
            echo "WF_ENF: ${WF_ENV}"
            echo "JOB_ENV: ${JOB_ENV}"
            echo "STEP_ENV: ${STEP_ENV}"
  
  log-defult-env:
    runs-on: ubuntu-latest
    steps:
      - name: paso2
        run: |
            echo "HOME: ${HOME}"
            echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
            echo "GITHUB_ACTION: ${GITHUB_ACTION}"
            echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
            echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
            echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
            echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
            echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
            echo "GITHUB_SHA: ${GITHUB_SHA}"
            echo "GITHUB_REF: ${GITHUB_REF}"
            echo "WF_ENF: ${WF_ENV}"
            echo "JOB_ENV: ${JOB_ENV}"
            echo "STEP_ENV: ${STEP_ENV}"