---
name: Actions en GitHub
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: See files
        run: ls -la
      - name: Checkout
        uses: actions/checkout@v2
      - name: See files
        run: ls -la
      - name: Crear Archivo Random
        run: |
          echo $RANDOM >> random.txt
          git config --global user.email "gianmarco@minelli.com"
          git config --global user.name "Gianmarco"
          git add random.txt
          git commit -m "Añadido Random File"
          git push