---
name: Actions en GitHub
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: See files
        run: ls -la
      - name: Checkout
        uses: actions/checkout@v2
      - name: See files
        run: ls -la
