---
name: Game of life testing
on: [push]

jobs:
  lgame-of-life-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: paso1
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.5.4
      - name: paso2
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: paso3
        run: |
            java -version 
            mvn -version
      - name: paso4
        run: git clone https://github.com/wakaleo/game-of-life.git .
      - name: paso5
        run: mvn test