---
name: Primer Workflow Gianmarco
on: 
  schedule:
    - cron: "*0/3 * * * * *"

jobs:
  prueba-con-cron:
   runs-on: ubuntu-20.04
   steps:
     - name: cron scheduler
       run: echo "--> Cron"

  #ejecutar-comandos-shell:
  #  runs-on: ubuntu-20.04
  #  steps:
  #    - name: echo cadena
  #      run: echo "Hello World"
  #    - name: scripts multitarea
  #      run: |
  #        mvn -v
  #        node -v
  #        cat /etc/os-release
  #    - name: Python console
  #      run: |
  ##        import platform
  #        print(platform.processor())
  #      shell: python
  #comandos-windows:
  #  runs-on: windows-latest
  #  steps:
  #    - name: Get-Location
  #      run: Get-Location
  #      shell: powershell
  #    - name: Bash pwd
  #      run: pwd
  #      shell: bash
  